; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Conservative upload speed for unstable USB-serial links
upload_speed = 57600
; upload_port = COM5
; monitor_port = COM5

; Use PlatformIO default reset sequence for ESP32
; upload_resetmethod = nodemcu

; Workaround for boards that fail after "Stub running..."
upload_flags =
    --no-stub

lib_deps =
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit Unified Sensor@^1.1.9
    bblanchon/ArduinoJson@^6.21.3